### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by pepa65** [imojiengineering/node-icu-tokenizer#1]
On Ubuntu 14.04 after installing from the standard repos, `npm install node-icu-tokenizer` fails with:
```
npm http GET https://registry.npmjs.org/node-icu-tokenizer
npm http 304 https://registry.npmjs.org/node-icu-tokenizer
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings

> node-icu-tokenizer@1.0.1 install /root/node_modules/node-icu-tokenizer
> node-gyp rebuild

make: Entering directory `/root/node_modules/node-icu-tokenizer/build'
  CXX(target) Release/obj.target/node-icu-tokenizer/node-icu-tokenizer.o
../node-icu-tokenizer.cpp:8:37: error: ‘FunctionCallbackInfo’ does not name a type
 void GetWordBoundaryPositions(const FunctionCallbackInfo<Value>& args) {
                                     ^
../node-icu-tokenizer.cpp:8:37: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../node-icu-tokenizer.cpp:8:57: error: expected ‘,’ or ‘...’ before ‘<’ token
 void GetWordBoundaryPositions(const FunctionCallbackInfo<Value>& args) {
                                                         ^
../node-icu-tokenizer.cpp: In function ‘void GetWordBoundaryPositions(int)’:
../node-icu-tokenizer.cpp:10:30: error: no matching function for call to ‘v8::HandleScope::HandleScope(v8::Isolate*&)’
     HandleScope scope(isolate);
                              ^
../node-icu-tokenizer.cpp:10:30: note: candidates are:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node-icu-tokenizer.cpp:1:
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
   HandleScope(const HandleScope&);
   ^
/usr/include/nodejs/deps/v8/include/v8.h:473:3: note:   no known conversion for argument 1 from ‘v8::Isolate*’ to ‘const v8::HandleScope&’
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note: v8::HandleScope::HandleScope()
   HandleScope();
   ^
/usr/include/nodejs/deps/v8/include/v8.h:448:3: note:   candidate expects 0 arguments, 1 provided
../node-icu-tokenizer.cpp:12:9: error: ‘args’ was not declared in this scope
     if (args.Length() != 2) {
         ^
../node-icu-tokenizer.cpp:13:18: error: ‘class v8::Isolate’ has no member named ‘ThrowException’
         isolate->ThrowException(Exception::TypeError(String::NewFromUtf8(isolate, "must supply locale and text")));
                  ^
../node-icu-tokenizer.cpp:59:63: error: no matching function for call to ‘v8::Object::New(v8::Isolate*&)’
             Local<Object> boundaryResult = Object::New(isolate);
                                                               ^
../node-icu-tokenizer.cpp:59:63: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node-icu-tokenizer.cpp:1:
/usr/include/nodejs/deps/v8/include/v8.h:1724:33: note: static v8::Local<v8::Object> v8::Object::New()
   V8EXPORT static Local<Object> New();
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1724:33: note:   candidate expects 0 arguments, 1 provided
../node-icu-tokenizer.cpp:60:33: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
             boundaryResult->Set(String::NewFromUtf8(isolate, "start"), Number::New(isolate, previousBoundary));
                                 ^
../node-icu-tokenizer.cpp:60:109: error: no matching function for call to ‘v8::Number::New(v8::Isolate*&, int32_t&)’
             boundaryResult->Set(String::NewFromUtf8(isolate, "start"), Number::New(isolate, previousBoundary));
                                                                                                             ^
../node-icu-tokenizer.cpp:60:109: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node-icu-tokenizer.cpp:1:
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
   V8EXPORT static Local<Number> New(double value);
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../node-icu-tokenizer.cpp:61:33: error: ‘NewFromUtf8’ is not a member of ‘v8::String’
             boundaryResult->Set(String::NewFromUtf8(isolate, "end"), Number::New(isolate, currentBoundary));
                                 ^
../node-icu-tokenizer.cpp:61:106: error: no matching function for call to ‘v8::Number::New(v8::Isolate*&, int32_t&)’
             boundaryResult->Set(String::NewFromUtf8(isolate, "end"), Number::New(isolate, currentBoundary));
                                                                                                          ^
../node-icu-tokenizer.cpp:61:106: note: candidate is:
In file included from /usr/include/nodejs/src/node.h:62:0,
                 from ../node-icu-tokenizer.cpp:1:
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note: static v8::Local<v8::Number> v8::Number::New(double)
   V8EXPORT static Local<Number> New(double value);
                                 ^
/usr/include/nodejs/deps/v8/include/v8.h:1377:33: note:   candidate expects 1 argument, 2 provided
../node-icu-tokenizer.cpp: In function ‘void Init(v8::Handle<v8::Object>)’:
../node-icu-tokenizer.cpp:77:82: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [25], void (&)(int))’
     NODE_SET_METHOD(exports, "getWordBoundaryPositions", GetWordBoundaryPositions);
                                                                                  ^
../node-icu-tokenizer.cpp:77:82: note: candidate is:
In file included from ../node-icu-tokenizer.cpp:1:0:
/usr/include/nodejs/src/node.h:112:6: note: template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
 void SetMethod(target_t obj, const char* name,
      ^
/usr/include/nodejs/src/node.h:112:6: note:   template argument deduction/substitution failed:
../node-icu-tokenizer.cpp:77:82: note:   cannot convert ‘GetWordBoundaryPositions’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
     NODE_SET_METHOD(exports, "getWordBoundaryPositions", GetWordBoundaryPositions);
                                                                                  ^
make: *** [Release/obj.target/node-icu-tokenizer/node-icu-tokenizer.o] Error 1
make: Leaving directory `/root/node_modules/node-icu-tokenizer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.19.0-56-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node_modules/node-icu-tokenizer
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 1
npm ERR! not ok code 0

```

**Comment by nkhoshini** [comment]
The module supports node versions 0.12 and higher. I've updated the package.json file to enforce that in version 1.0.2

**Comment by pepa65** [comment]
I don't know how to get the new package. I did `npm update` but still fails with the same version number.

**Comment by nkhoshini** [comment]
You'll need to update your Nodejs version to 0.12.x or later. I don't have the engine-strict setting enabled in the package.json so you won't get an warning message saying your Nodejs version is not supported.
